export const GLVAL = {
  GL_FRAMEBUFFER: 0x8d40,
  GL_RENDERBUFFER: 0x8d41,
  GL_TEXTURE_2D: 0x0de1,
  GL_TEXTURE_CUBE_MAP: 0x8513,
  GL_TEXTURE_CUBE_MAP_POSITIVE_X: 0x8515,

  GL_COLOR_ATTACHMENT0: 0x8ce0,
  GL_DEPTH_ATTACHMENT: 0x8d00,
  GL_STENCIL_ATTACHMENT: 0x8d20,
  GL_DEPTH_STENCIL_ATTACHMENT: 0x821a,

  GL_FRAMEBUFFER_COMPLETE: 0x8cd5,
  GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT: 0x8cd6,
  GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: 0x8cd7,
  GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS: 0x8cd9,
  GL_FRAMEBUFFER_UNSUPPORTED: 0x8cdd,

  GL_HALF_FLOAT_OES: 0x8d61,
  GL_UNSIGNED_BYTE: 0x1401,
  GL_FLOAT: 0x1406,

  GL_RGB: 0x1907,
  GL_RGBA: 0x1908,
  GL_DEPTH_COMPONENT: 0x1902,

  GL_RGBA4: 0x8056,
  GL_RGB5_A1: 0x8057,
  GL_RGB565: 0x8d62,

  GL_DEPTH_COMPONENT16: 0x81a5,
  GL_STENCIL_INDEX8: 0x8d48,
  GL_DEPTH_STENCIL: 0x84f9,

  GL_SRGB8_ALPHA8_EXT: 0x8c43,
  GL_RGBA32F_EXT: 0x8814,
  GL_RGBA16F_EXT: 0x881a,
  GL_RGB16F_EXT: 0x881b,

  GL_SUBPIXEL_BITS: 0x0d50,
  GL_RED_BITS: 0x0d52,
  GL_GREEN_BITS: 0x0d53,
  GL_BLUE_BITS: 0x0d54,
  GL_ALPHA_BITS: 0x0d55,
  GL_DEPTH_BITS: 0x0d56,
  GL_STENCIL_BITS: 0x0d57,

  GL_ALIASED_POINT_SIZE_RANGE: 0x846d,
  GL_ALIASED_LINE_WIDTH_RANGE: 0x846e,

  GL_MAX_TEXTURE_SIZE: 0x0d33,
  GL_MAX_VIEWPORT_DIMS: 0x0d3a,
  GL_MAX_VERTEX_ATTRIBS: 0x8869,
  GL_MAX_VERTEX_UNIFORM_VECTORS: 0x8dfb,
  GL_MAX_VARYING_VECTORS: 0x8dfc,
  GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: 0x8b4d,
  GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: 0x8b4c,
  GL_MAX_TEXTURE_IMAGE_UNITS: 0x8872,
  GL_MAX_FRAGMENT_UNIFORM_VECTORS: 0x8dfd,
  GL_MAX_CUBE_MAP_TEXTURE_SIZE: 0x851c,
  GL_MAX_RENDERBUFFER_SIZE: 0x84e8,

  GL_VENDOR: 0x1f00,
  GL_RENDERER: 0x1f01,
  GL_VERSION: 0x1f02,
  GL_SHADING_LANGUAGE_VERSION: 0x8b8c,

  GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT: 0x84ff,

  GL_MAX_COLOR_ATTACHMENTS_WEBGL: 0x8cdf,
  GL_MAX_DRAW_BUFFERS_WEBGL: 0x8824,

  GL_TEXTURE0: 0x84c0,
  GL_COLOR_BUFFER_BIT: 0x4000
} as const;

export const GLENUM = {
  colorTextureFormat: [GLVAL.GL_RGB, GLVAL.GL_RGBA],
  colorRenderbufferFormat: [
    GLVAL.GL_RGBA4,
    GLVAL.GL_RGB5_A1,
    GLVAL.GL_RGB565,
    GLVAL.GL_SRGB8_ALPHA8_EXT,
    GLVAL.GL_RGBA16F_EXT,
    GLVAL.GL_RGB16F_EXT,
    GLVAL.GL_RGBA32F_EXT
  ],
  /** Maps texture format to number of channels. */
  textureFormatChannels: {
    [GLVAL.GL_RGB]: 3,
    [GLVAL.GL_RGBA]: 4
  },
  /** Maps texture type to byte count. */
  textureTypeSizes: {
    [GLVAL.GL_UNSIGNED_BYTE]: 1,
    [GLVAL.GL_FLOAT]: 4,
    [GLVAL.GL_HALF_FLOAT_OES]: 2
  },
  statusCode: {
    [GLVAL.GL_FRAMEBUFFER_COMPLETE]: "complete",
    [GLVAL.GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT]: "incomplete attachment",
    [GLVAL.GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS]: "incomplete dimensions",
    [GLVAL.GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT]:
      "incomplete, missing attachment",
    [GLVAL.GL_FRAMEBUFFER_UNSUPPORTED]: "unsupported"
  }
} as const;
